parameters:

services:
    braincrafted.bootstrap.voter.request:
        class: Braincrafted\BootstrapBundle\Voter\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }
    braincrafted.bootstrap.voter.request.regex:
        class: Braincrafted\BootstrapBundle\Voter\RequestRegexVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }
    braincrafted.twig.bootstrap_icon_extension:
        class: Braincrafted\BootstrapBundle\Twig\BootstrapIconExtension
        tags:
            - { name: twig.extension }
    braincrafted.twig.bootstrap_label_extension:
        class: Braincrafted\BootstrapBundle\Twig\BootstrapLabelExtension
        tags:
            - { name: twig.extension }
